### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by skelgaard** [boggan/web-videochat#1]
$ node main.js

/****/server/js/NetworkMgr.js:236
        let l_sName = i_oMsg.data,
            ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/....../server/main.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by boggan** [comment]
it seems your version of nodejs might be a bit old and it did not like the "let" operator, I think if you update it to the latest version it should work :)

**Comment by skelgaard** [comment]
thanx i will check and update it... i just use the version that is in debian

**Comment by skelgaard** [comment]
ok that worked, now i just need to find out how to make it work on a domain instead of 8080 as i run it on my server to test, not my machine :)

**Comment by skelgaard** [comment]
ah works... thanx :)

**Comment by boggan** [comment]
My pleasure :) It's still a work in progress, and since I don't have a lot of time for personnal development, let me know if you find any bugs / features you would like implemented !!

**Comment by skelgaard** [comment]
well its not near anything useful yet for my purpose :) was looking for something like webrtc-chat.com with flashfallback but as self hosted and developed instead.
so anything with crude many to many video/audio and chat in it and then just needs a lot of fine tuning :)

i have yet to find any projects that does that, that i can use as a base for what i'm trying to build :)
